version: '3.8'
services:
  db:
    image: mariadb:10.6.11
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/mariadb-admin.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/classicmodels.sql:/docker-entrypoint-initdb.d/2.sql"
            
    environment:
      MARIADB_ROOT_PASSWORD: root