version: '3.8'
services:
  db1:
    image: mariadb:10.6.11
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/sakila-schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/sakila-data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
  
  db2:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./scripts/sakila-schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/sakila-data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
