version: '3.8'
services:
  db:
    image: mariadb:10.6.11
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/sakila-schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/sakila-data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/admin.sql:/docker-entrypoint-initdb.d/3.sql"
    environment:
      MARIADB_ROOT_PASSWORD: root
